/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountCard: typeof import('./../components/AccountCard.vue')['default']
    AuthenticatedPage: typeof import('./../components/AuthenticatedPage.vue')['default']
    Button: typeof import('./../components/Button.vue')['default']
    GlassCard: typeof import('./../components/GlassCard.vue')['default']
    LandingPage: typeof import('./../components/LandingPage.vue')['default']
    LoadingSpinner: typeof import('./../components/LoadingSpinner.vue')['default']
    LogViewer: typeof import('./../components/LogViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusIndicator: typeof import('./../components/StatusIndicator.vue')['default']
    Toast: typeof import('./../components/Toast.vue')['default']
  }
}
