/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountCard: typeof import('./../components/business/AccountCard.vue')['default']
    AccountSwitcher: typeof import('./../components/business/AccountSwitcher.vue')['default']
    AddAccountDialog: typeof import('./../components/business/AddAccountDialog.vue')['default']
    AppHeader: typeof import('./../components/layout/AppHeader.vue')['default']
    AuthenticatedPage: typeof import('./../components/AuthenticatedPage.vue')['default']
    Button: typeof import('./../components/ui/Button.vue')['default']
    CandidateList: typeof import('./../components/business/CandidateList.vue')['default']
    CandidateSearch: typeof import('./../components/business/CandidateSearch.vue')['default']
    GlassCard: typeof import('./../components/ui/GlassCard.vue')['default']
    Icon: typeof import('./../components/ui/Icon.vue')['default']
    JobManager: typeof import('./../components/business/JobManager.vue')['default']
    LandingPage: typeof import('./../components/LandingPage.vue')['default']
    LoadingSpinner: typeof import('./../components/ui/LoadingSpinner.vue')['default']
    LogViewer: typeof import('./../components/LogViewer.vue')['default']
    NavItem: typeof import('./../components/navigation/NavItem.vue')['default']
    ReplyRuleManager: typeof import('./../components/business/ReplyRuleManager.vue')['default']
    ResumeManager: typeof import('./../components/business/ResumeManager.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusIndicator: typeof import('./../components/ui/StatusIndicator.vue')['default']
    TaskManager: typeof import('./../components/business/TaskManager.vue')['default']
    Toast: typeof import('./../components/ui/Toast.vue')['default']
  }
}
